version: '3.8'
services:
  nginx:
    image: nginx:1.23.3
    ports:
      - 80:80
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    # docker compose -p qlcdv-nginx up -d
